# Vagrantfile for multi-VM setup with two Ubuntu Focal 64 machines

Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/focal64"

  # VM1 configuration
  config.vm.define "SonarQube" do |vm1|
    vm1.vm.hostname = "SonarQube"
    vm1.vm.network "public_network", ip: "192.168.0.206"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
  config.vm.define "SonarTypeNexus" do |vm2|
    vm2.vm.hostname = "SonarTypeNexus"
    vm2.vm.network "public_network", ip: "192.168.0.207"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end       