# Vagrantfile for multi-VM setup with two Ubuntu Focal 64 machines

Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/focal64"

  # VM1 configuration
  config.vm.define "Prometheus" do |vm1|
    vm1.vm.hostname = "prometheus"
    vm1.vm.network "public_network", ip: "192.168.0.205"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
      vm1.vm.provision "shell", path:"./install.sh"
  end
end       